version: '2'
services:
  map-server:
    build:
      context: .
      dockerfile: Dockerfile_build
    image: ollebo/mapserver
    volumes:
      - ./web:/data/web
      - ./maps:/data/maps
      - ./:/code
    ports:
      - 8888:8080
    environment:
      - API=http://api.ollebo.com



 


