FROM ubuntu:24.04

EXPOSE 8080
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /code
WORKDIR /code

RUN apt-get update && apt-get install -y python3-pip gdal-bin libgdal-dev python3-gdal \
    && rm -rf /var/lib/apt/lists/*

COPY ./code/requirements.txt /code/
RUN pip install -r /code/requirements.txt --break-system-packages --ignore-installed

RUN mkdir -p /data/maps /data/cogs /data/db

COPY ./code /code/
RUN chmod +x /code/start.sh

CMD ["/code/start.sh"]
