apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapserver.fullname" . }}
  labels:
    {{- include "mapserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mapserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: flask
      port: {{ .Values.service.flaskPort }}
      targetPort: flask
      protocol: TCP
    - name: terracotta
      port: {{ .Values.service.terracottaPort }}
      targetPort: terracotta
      protocol: TCP
